export const teamMembers = [
  {
    name: "Timo Lars Fuhlbrügge",
    role: "Gründer und Geschäftsführer",
    desciption: "Nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat",
    image: "/images/timo.png",
    color: "yellow",
    shapes: ["crosshatch","eye","eye-small","scribble","curve","blob-small",],
  },
  {
    name: "Jasmin Fuhlbrügge",
    role: "Gründer & Marketingleiter",
    desciption: "Nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat",
    image: "/images/jasmin.png",
    color: "pink",
    shapes: ["scribble","dots","blob","blob-small","branch","bottom-wave",],
  },
  {
    name: "Michelle Nagel",
    role: "Leitender Designer",
    desciption: "Nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat",
    image: "/images/portrait-1.png",
    color: "blue",
    shapes: ["top-wave","blob","blob-small","star","curve","bottom-blob",],
  },
  {
    name: "Maik Eberhardt",
    role: "Leitender Designer",
    image: "/images/portrait-2.png",
    color: "yellow",
    shapes: ["crosshatch","eye","eye-small","scribble","curve","blob-small",],
  },
  {
    name: "Sebastian Jager",
    role: "Leitender Designer",
    image: "/images/portrait-1.png",
    color: "blue",
    shapes: ["top-wave","blob","blob-small","star","curve","bottom-blob",],
  },
  {
    name: "Matthias Kalb",
    role: "Leitender Designer",
    image: "/images/portrait-1.png",
    color: "yellow",
    shapes: ["crosshatch","eye","eye-small","scribble","curve","blob-small",],
  },
  {
    name: "Marko Reiniger",
    role: "Leitender Designer",
    image: "/images/portrait-1.png",
    color: "blue",
    shapes: ["top-wave","blob","blob-small","star","curve","bottom-blob",],
  },
  {
    name: "Lea Klug",
    role: "Leitender Designer",
    image: "/images/portrait-3.png",
    color: "pink",
    shapes: ["scribble","dots","blob","blob-small","branch","bottom-wave",],
  },
  {
    name: "Jürgen König",
    role: "Leitender Designer",
    image: "/images/portrait-1.png",
    color: "blue",
    shapes: ["top-wave","blob","blob-small","star","curve","bottom-blob",],
  },
];